# 1_D array


In [2]:
import numpy as np
food=np.array(["samosa","pakora","raita"])
food

array(['samosa', 'pakora', 'raita'], dtype='<U6')

In [3]:
price =np.array([5,5,5])
price


array([5, 5, 5])

In [4]:
type(price)

numpy.ndarray

In [5]:
type(food)

numpy.ndarray

In [8]:
len(food)

3

In [9]:
price[2]

5

In [10]:
price[0:]

array([5, 5, 5])

In [11]:
food[0]

'samosa'

In [12]:
food[1:]

array(['pakora', 'raita'], dtype='<U6')

In [13]:
price.mean()

5.0

In [15]:
#zero method 
np.zeros(6)


array([0., 0., 0., 0., 0., 0.])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [18]:
#range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(2,20)


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [23]:
np.arange(2 , 20,3)

array([ 2,  5,  8, 11, 14, 17])

In [24]:
#table
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [26]:
np.linspace(1, 100, num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [29]:
# specify your data type
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [30]:
# specify your data type
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
a = np.array([12,34,56,10,4,77,100,0.5])
a

array([ 12. ,  34. ,  56. ,  10. ,   4. ,  77. , 100. ,   0.5])

In [33]:
a.sort()
a

array([  0.5,   4. ,  10. ,  12. ,  34. ,  56. ,  77. , 100. ])

In [34]:
b=np.array([9,55,0.5,77,3,0.7])
b

array([ 9. , 55. ,  0.5, 77. ,  3. ,  0.7])

In [38]:
c=np.concatenate((a,b))
np.sort(c)

array([  0.5,   0.5,   0.7,   3. ,   4. ,   9. ,  10. ,  12. ,  34. ,
        55. ,  56. ,  77. ,  77. , 100. ])

## 2-d_array

In [39]:
a=np.array([[1,2,3,4,5], [6,7,8,9,0]])
a

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [42]:
b=np.array([[0,9,8,7,6],[5,4,3,2,1]])
b

array([[0, 9, 8, 7, 6],
       [5, 4, 3, 2, 1]])

In [43]:
d=np.concatenate((a,b))
d

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [0, 9, 8, 7, 6],
       [5, 4, 3, 2, 1]])